name: quantum_fetch
description: a flutter package to make api call.
version: 0.2.1-beta
homepage: https://github.com/santoshacharya2468/flutter_quantum_fetch
repository: https://github.com/santoshacharya2468/flutter_quantum_fetch


environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  http_parser: ^4.0.2
  pretty_dio_logger: ^1.3.1
  mime: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
flutter:

